[package]
name = "egconf"
version = "0.1.0"
authors = ["ICEY <icey@icey.tech>"]
edition = "2018"

license-file = "LICENSE"
description = "EasyGoing Configuration"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
